import express from 'express';
import { updateProblem,editProblemInfo, addProblemWithTestcases ,fetchProblems,deleteProblem,getAdminStats} from '../controller/adminController.js';
const router = express.Router();
router.post('/addproblems', addProblemWithTestcases);
router.get('/problems', fetchProblems);
router.delete('/delete/:id', deleteProblem); 
router.get("/editProblem/:id",editProblemInfo);
router.put("/update/:id", updateProblem);
router.get("/stats", getAdminStats);
export default router;
